-- DO NOT EXECUTE WITHOUT EXPLICIT USER APPROVAL
--
-- Review-only MySQL 8 schema proposal for 803 Jianshi research modules.
-- This file contains no seed data and has not been run against any database.
-- All DATETIME(3) values are application/business times in Asia/Shanghai.
-- Existing raw market tables remain authoritative and are intentionally not
-- recreated here: daily, daily_basic, adj_factor, index_basic, index_daily,
-- and the live-audit-pending call_auction table.

CREATE TABLE `stock_basic` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ts_code` VARCHAR(16) NOT NULL,
  `symbol` VARCHAR(12) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `full_name` VARCHAR(255) NULL,
  `exchange` VARCHAR(16) NOT NULL,
  `market` VARCHAR(32) NULL,
  `board` VARCHAR(64) NULL,
  `industry` VARCHAR(128) NULL,
  `list_status` VARCHAR(24) NOT NULL,
  `list_date` DATE NULL,
  `delist_date` DATE NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_stock_basic_ts_code` (`ts_code`),
  UNIQUE KEY `uq_stock_basic_exchange_symbol` (`exchange`, `symbol`),
  KEY `idx_stock_basic_candidate_filter` (`list_status`, `board`, `industry`, `ts_code`),
  CONSTRAINT `chk_stock_basic_list_status` CHECK (`list_status` IN ('listed', 'paused', 'delisted', 'pending'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `trade_calendar` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `exchange` VARCHAR(16) NOT NULL,
  `trade_date` DATE NOT NULL,
  `is_open` BOOLEAN NOT NULL,
  `previous_trade_date` DATE NULL,
  `session_open_time` TIME(3) NULL,
  `session_close_time` TIME(3) NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_trade_calendar_exchange_date` (`exchange`, `trade_date`),
  KEY `idx_trade_calendar_market_status` (`trade_date`, `is_open`, `exchange`),
  KEY `idx_trade_calendar_previous_date` (`exchange`, `previous_trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `stock_limit_price` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `stock_id` BIGINT UNSIGNED NOT NULL,
  `trade_date` DATE NOT NULL,
  `up_limit_price` DECIMAL(20,4) NOT NULL,
  `down_limit_price` DECIMAL(20,4) NOT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_stock_limit_price_stock_date` (`stock_id`, `trade_date`),
  KEY `idx_stock_limit_price_date_down` (`trade_date`, `down_limit_price`, `stock_id`),
  CONSTRAINT `fk_stock_limit_price_stock` FOREIGN KEY (`stock_id`) REFERENCES `stock_basic` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_stock_limit_price_order` CHECK (`down_limit_price` <= `up_limit_price`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `external_market_quote` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(32) NOT NULL,
  `market_name` VARCHAR(128) NOT NULL,
  `quote_at` DATETIME(3) NOT NULL,
  `session_type` VARCHAR(24) NOT NULL,
  `currency` CHAR(3) NULL,
  `open_price` DECIMAL(20,6) NULL,
  `high_price` DECIMAL(20,6) NULL,
  `low_price` DECIMAL(20,6) NULL,
  `close_price` DECIMAL(20,6) NULL,
  `previous_close_price` DECIMAL(20,6) NULL,
  `change_rate_pct` DECIMAL(12,6) NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_external_quote_symbol_time_session` (`symbol`, `quote_at`, `session_type`),
  KEY `idx_external_quote_latest` (`symbol`, `quote_at`, `data_as_of`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `market_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_code` VARCHAR(64) NOT NULL,
  `event_date` DATE NOT NULL,
  `starts_at` DATETIME(3) NULL,
  `ends_at` DATETIME(3) NULL,
  `category` VARCHAR(64) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `summary` TEXT NULL,
  `event_status` VARCHAR(24) NOT NULL,
  `related_sector` VARCHAR(128) NULL,
  `related_symbol` VARCHAR(32) NULL,
  `importance` VARCHAR(16) NULL,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_market_event_code` (`event_code`),
  UNIQUE KEY `uq_market_event_source_record` (`source_name`, `source_record_id`),
  KEY `idx_market_event_month_list` (`event_date`, `event_status`, `sort_order`),
  CONSTRAINT `chk_market_event_status` CHECK (`event_status` IN ('scheduled', 'confirmed', 'completed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `intel_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(128) NULL,
  `content_kind` VARCHAR(64) NULL,
  `attention_action` VARCHAR(32) NULL,
  `sector` VARCHAR(128) NULL,
  `title` VARCHAR(255) NOT NULL,
  `body_summary` TEXT NULL,
  `change_summary` VARCHAR(512) NULL,
  `importance` VARCHAR(16) NULL,
  `published_at` DATETIME(3) NOT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NOT NULL,
  `source_record_id` VARCHAR(191) NOT NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_intel_item_source_record` (`source_name`, `source_record_id`),
  KEY `idx_intel_item_feed_filter` (`published_at`, `author_name`, `attention_action`, `sector`),
  CONSTRAINT `chk_intel_item_importance` CHECK (`importance` IS NULL OR `importance` IN ('low', 'medium', 'high'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `research_batch` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_code` VARCHAR(64) NOT NULL,
  `module` VARCHAR(32) NOT NULL,
  `trade_date` DATE NOT NULL,
  `status` VARCHAR(16) NOT NULL,
  `started_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NULL,
  `records_total` BIGINT UNSIGNED NULL,
  `records_completed` BIGINT UNSIGNED NULL,
  `records_missing` BIGINT UNSIGNED NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_batch_ref` VARCHAR(191) NULL,
  `pipeline_version` VARCHAR(64) NOT NULL,
  `error_message` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_research_batch_code` (`batch_code`),
  UNIQUE KEY `uq_research_batch_id_trade_date_status` (`id`, `trade_date`, `status`),
  UNIQUE KEY `uq_research_batch_module_date_code` (`module`, `trade_date`, `batch_code`),
  KEY `idx_research_batch_latest_successful_batch` (`module`, `trade_date`, `status`, `completed_at`, `id`),
  CONSTRAINT `chk_research_batch_module` CHECK (`module` IN ('today', 'risk', 'strategy', 'ipo')),
  CONSTRAINT `chk_research_batch_status` CHECK (`status` IN ('pending', 'running', 'success', 'partial', 'failed')),
  CONSTRAINT `chk_research_batch_terminal_times` CHECK (
    `status` NOT IN ('success', 'partial')
    OR (`completed_at` IS NOT NULL AND `data_as_of` IS NOT NULL)
  ),
  CONSTRAINT `chk_research_batch_time_order` CHECK (
    `started_at` IS NULL OR `completed_at` IS NULL OR `completed_at` >= `started_at`
  ),
  CONSTRAINT `chk_research_batch_counts` CHECK (
    (`records_total` IS NULL OR `records_completed` IS NULL OR `records_completed` <= `records_total`)
    AND (`records_total` IS NULL OR `records_missing` IS NULL OR `records_missing` <= `records_total`)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `daily_decision_snapshot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_batch_id` BIGINT UNSIGNED NOT NULL,
  `market_stage` VARCHAR(64) NULL,
  `headline` VARCHAR(255) NULL,
  `summary` TEXT NULL,
  `action_text` TEXT NULL,
  `summary_points_json` JSON NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_daily_decision_batch` (`research_batch_id`),
  KEY `idx_daily_decision_as_of` (`data_as_of`, `research_batch_id`),
  CONSTRAINT `fk_daily_decision_batch` FOREIGN KEY (`research_batch_id`) REFERENCES `research_batch` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `risk_snapshot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_batch_id` BIGINT UNSIGNED NOT NULL,
  `risk_score` DECIMAL(6,2) NULL,
  `stage_code` VARCHAR(32) NULL,
  `stage_label` VARCHAR(64) NULL,
  `risk_coefficient_pct` DECIMAL(7,4) NULL,
  `exposure_constraint_pct` DECIMAL(7,4) NULL,
  `current_data_layer` VARCHAR(128) NULL,
  `summary` TEXT NULL,
  `action_text` TEXT NULL,
  `kill_condition_hit_count` SMALLINT UNSIGNED NULL,
  `kill_condition_total_count` SMALLINT UNSIGNED NULL,
  `kill_switch_triggered` BOOLEAN NULL,
  `timeline_json` JSON NULL,
  `kill_conditions_json` JSON NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_risk_snapshot_batch` (`research_batch_id`),
  KEY `idx_risk_snapshot_as_of` (`data_as_of`, `research_batch_id`),
  CONSTRAINT `fk_risk_snapshot_batch` FOREIGN KEY (`research_batch_id`) REFERENCES `research_batch` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_risk_snapshot_score` CHECK (`risk_score` IS NULL OR (`risk_score` >= 0 AND `risk_score` <= 100)),
  CONSTRAINT `chk_risk_snapshot_kill_counts` CHECK (
    `kill_condition_hit_count` IS NULL OR `kill_condition_total_count` IS NULL OR `kill_condition_hit_count` <= `kill_condition_total_count`
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `risk_signal_result` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `risk_snapshot_id` BIGINT UNSIGNED NOT NULL,
  `signal_code` VARCHAR(64) NOT NULL,
  `signal_label` VARCHAR(128) NOT NULL,
  `display_value` VARCHAR(255) NULL,
  `raw_numeric_value` DECIMAL(24,8) NULL,
  `historical_percentile_pct` DECIMAL(7,4) NULL,
  `threshold_text` VARCHAR(255) NULL,
  `contribution_score` DECIMAL(8,4) NULL,
  `signal_status` VARCHAR(24) NULL,
  `explanation` TEXT NULL,
  `sort_order` INT UNSIGNED NOT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_risk_signal_snapshot_code` (`risk_snapshot_id`, `signal_code`),
  UNIQUE KEY `uq_risk_signal_snapshot_order` (`risk_snapshot_id`, `sort_order`),
  KEY `idx_risk_signal_status` (`risk_snapshot_id`, `signal_status`, `sort_order`),
  CONSTRAINT `fk_risk_signal_snapshot` FOREIGN KEY (`risk_snapshot_id`) REFERENCES `risk_snapshot` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_risk_signal_percentile` CHECK (`historical_percentile_pct` IS NULL OR (`historical_percentile_pct` >= 0 AND `historical_percentile_pct` <= 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `strategy_definition` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `strategy_code` VARCHAR(64) NOT NULL,
  `version` VARCHAR(32) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` TEXT NULL,
  `is_enabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `rules_json` JSON NOT NULL,
  `effective_from` DATETIME(3) NOT NULL,
  `effective_to` DATETIME(3) NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_strategy_definition_code_version` (`strategy_code`, `version`),
  KEY `idx_strategy_definition_active` (`strategy_code`, `is_enabled`, `effective_from`, `effective_to`),
  CONSTRAINT `chk_strategy_definition_code` CHECK (`strategy_code` = 'momentum-gap-volume')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `strategy_run` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_batch_id` BIGINT UNSIGNED NOT NULL,
  `strategy_definition_id` BIGINT UNSIGNED NOT NULL,
  `trade_date` DATE NOT NULL,
  `run_status` VARCHAR(16) NOT NULL,
  `market_sample_count` BIGINT UNSIGNED NULL,
  `official_candidate_count` BIGINT UNSIGNED NULL,
  `near_candidate_count` BIGINT UNSIGNED NULL,
  `runtime_ms` BIGINT UNSIGNED NULL,
  `started_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_strategy_run_batch` (`research_batch_id`),
  UNIQUE KEY `uq_strategy_run_definition_date_batch` (`strategy_definition_id`, `trade_date`, `research_batch_id`),
  KEY `idx_strategy_run_latest_successful_batch` (`strategy_definition_id`, `trade_date`, `run_status`, `completed_at`, `id`),
  CONSTRAINT `fk_strategy_run_batch_date_status` FOREIGN KEY (`research_batch_id`, `trade_date`, `run_status`) REFERENCES `research_batch` (`id`, `trade_date`, `status`) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `fk_strategy_run_definition` FOREIGN KEY (`strategy_definition_id`) REFERENCES `strategy_definition` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_strategy_run_status` CHECK (`run_status` IN ('pending', 'running', 'success', 'partial', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `strategy_funnel_result` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `strategy_run_id` BIGINT UNSIGNED NOT NULL,
  `step_code` VARCHAR(64) NOT NULL,
  `step_name` VARCHAR(128) NOT NULL,
  `passed_count` BIGINT UNSIGNED NOT NULL,
  `sort_order` INT UNSIGNED NOT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_strategy_funnel_run_step` (`strategy_run_id`, `step_code`),
  UNIQUE KEY `uq_strategy_funnel_run_order` (`strategy_run_id`, `sort_order`),
  CONSTRAINT `fk_strategy_funnel_run` FOREIGN KEY (`strategy_run_id`) REFERENCES `strategy_run` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `strategy_candidate` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `strategy_run_id` BIGINT UNSIGNED NOT NULL,
  `stock_id` BIGINT UNSIGNED NOT NULL,
  `candidate_type` VARCHAR(16) NOT NULL,
  `rank_no` INT UNSIGNED NULL,
  `match_score` DECIMAL(7,4) NULL,
  `close_price` DECIMAL(20,4) NULL,
  `change_rate_pct` DECIMAL(12,6) NULL,
  `gap_rate_pct` DECIMAL(12,6) NULL,
  `volume_ratio` DECIMAL(16,6) NULL,
  `setup_label` VARCHAR(255) NULL,
  `reason_text` TEXT NULL,
  `evidence_json` JSON NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_strategy_candidate_run_stock` (`strategy_run_id`, `stock_id`),
  KEY `idx_strategy_candidate_candidate_filter` (`strategy_run_id`, `candidate_type`, `match_score`, `rank_no`, `stock_id`),
  CONSTRAINT `fk_strategy_candidate_run` FOREIGN KEY (`strategy_run_id`) REFERENCES `strategy_run` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `fk_strategy_candidate_stock` FOREIGN KEY (`stock_id`) REFERENCES `stock_basic` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_strategy_candidate_type` CHECK (`candidate_type` IN ('official', 'near')),
  CONSTRAINT `chk_strategy_candidate_score` CHECK (`match_score` IS NULL OR (`match_score` >= 0 AND `match_score` <= 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ipo_company` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `exchange` VARCHAR(32) NULL,
  `board` VARCHAR(64) NULL,
  `industry` VARCHAR(128) NULL,
  `ts_code` VARCHAR(16) NULL,
  `current_status` VARCHAR(64) NULL,
  `summary` TEXT NULL,
  `core_product` TEXT NULL,
  `research_focus` TEXT NULL,
  `demand_drivers` TEXT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NOT NULL,
  `source_record_id` VARCHAR(191) NOT NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ipo_company_code` (`company_code`),
  UNIQUE KEY `uq_ipo_company_ts_code` (`ts_code`),
  UNIQUE KEY `uq_ipo_company_source_record` (`source_name`, `source_record_id`),
  KEY `idx_ipo_company_status` (`current_status`, `exchange`, `board`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ipo_stage_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ipo_company_id` BIGINT UNSIGNED NOT NULL,
  `stage_code` VARCHAR(32) NOT NULL,
  `stage_name` VARCHAR(64) NOT NULL,
  `event_date` DATE NULL,
  `event_at` DATETIME(3) NULL,
  `completion_status` VARCHAR(24) NOT NULL,
  `description` TEXT NULL,
  `sort_order` INT UNSIGNED NOT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NOT NULL,
  `source_record_id` VARCHAR(191) NOT NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ipo_stage_source_record` (`source_name`, `source_record_id`),
  UNIQUE KEY `uq_ipo_stage_company_position` (`ipo_company_id`, `stage_code`, `sort_order`),
  KEY `idx_ipo_stage_company_timeline` (`ipo_company_id`, `event_date`, `sort_order`),
  CONSTRAINT `fk_ipo_stage_company` FOREIGN KEY (`ipo_company_id`) REFERENCES `ipo_company` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_ipo_stage_status` CHECK (`completion_status` IN ('complete', 'current', 'planned', 'incomplete', 'unknown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ipo_metric_snapshot` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_batch_id` BIGINT UNSIGNED NOT NULL,
  `ipo_company_id` BIGINT UNSIGNED NOT NULL,
  `snapshot_kind` VARCHAR(32) NOT NULL,
  `metrics_json` JSON NOT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NOT NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ipo_metric_company_batch_kind` (`ipo_company_id`, `research_batch_id`, `snapshot_kind`),
  KEY `idx_ipo_metric_latest_successful_batch` (`ipo_company_id`, `data_as_of`, `research_batch_id`),
  CONSTRAINT `fk_ipo_metric_batch` FOREIGN KEY (`research_batch_id`) REFERENCES `research_batch` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `fk_ipo_metric_company` FOREIGN KEY (`ipo_company_id`) REFERENCES `ipo_company` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ipo_subscription_analysis` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_batch_id` BIGINT UNSIGNED NOT NULL,
  `ipo_company_id` BIGINT UNSIGNED NOT NULL,
  `analysis_type` VARCHAR(16) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'CNY',
  `issue_shares` BIGINT UNSIGNED NULL,
  `fundraising_amount` DECIMAL(24,4) NULL,
  `issue_price` DECIMAL(20,4) NULL,
  `single_lot_shares` BIGINT UNSIGNED NULL,
  `single_lot_funds` DECIMAL(24,4) NULL,
  `top_subscription_shares` BIGINT UNSIGNED NULL,
  `required_market_cap` DECIMAL(24,4) NULL,
  `allocation_number_count` BIGINT UNSIGNED NULL,
  `winning_rate_pct` DECIMAL(12,8) NULL,
  `at_least_one_win_probability_pct` DECIMAL(12,8) NULL,
  `calculation_basis` TEXT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NOT NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ipo_subscription_company_batch_type` (`ipo_company_id`, `research_batch_id`, `analysis_type`),
  KEY `idx_ipo_subscription_latest_successful_batch` (`ipo_company_id`, `data_as_of`, `research_batch_id`),
  CONSTRAINT `fk_ipo_subscription_batch` FOREIGN KEY (`research_batch_id`) REFERENCES `research_batch` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `fk_ipo_subscription_company` FOREIGN KEY (`ipo_company_id`) REFERENCES `ipo_company` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `chk_ipo_subscription_type` CHECK (`analysis_type` IN ('actual', 'scenario')),
  CONSTRAINT `chk_ipo_subscription_rate` CHECK (`winning_rate_pct` IS NULL OR (`winning_rate_pct` >= 0 AND `winning_rate_pct` <= 100)),
  CONSTRAINT `chk_ipo_subscription_at_least_one_probability` CHECK (`at_least_one_win_probability_pct` IS NULL OR (`at_least_one_win_probability_pct` >= 0 AND `at_least_one_win_probability_pct` <= 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ipo_valuation_scenario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `research_batch_id` BIGINT UNSIGNED NOT NULL,
  `ipo_company_id` BIGINT UNSIGNED NOT NULL,
  `scenario_code` VARCHAR(64) NOT NULL,
  `scenario_label` VARCHAR(128) NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'CNY',
  `scenario_price` DECIMAL(20,4) NULL,
  `floating_shares` BIGINT UNSIGNED NULL,
  `total_shares` BIGINT UNSIGNED NULL,
  `floating_market_cap` DECIMAL(24,4) NULL,
  `total_market_cap` DECIMAL(24,4) NULL,
  `is_official` BOOLEAN NOT NULL DEFAULT FALSE,
  `calculation_basis` TEXT NULL,
  `source_name` VARCHAR(128) NOT NULL,
  `source_url` VARCHAR(1024) NOT NULL,
  `source_record_id` VARCHAR(191) NULL,
  `source_published_at` DATETIME(3) NULL,
  `data_as_of` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ipo_valuation_company_batch_scenario` (`ipo_company_id`, `research_batch_id`, `scenario_code`),
  KEY `idx_ipo_valuation_scenario_filter` (`ipo_company_id`, `research_batch_id`, `scenario_price`, `floating_shares`),
  CONSTRAINT `fk_ipo_valuation_batch` FOREIGN KEY (`research_batch_id`) REFERENCES `research_batch` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT `fk_ipo_valuation_company` FOREIGN KEY (`ipo_company_id`) REFERENCES `ipo_company` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
